services:
  backend:
    build: ./be
    ports:
      - "8000:8000"
    volumes:
      - ./be:/var/www # bind source code
      - backend_vendor:/var/www/vendor # named volume giá»¯ vendor
    depends_on:
      - db
    networks:
      - appnet

  frontend:
    build: ./fe
    ports:
      - "5173:5173"
    volumes:
      - ./fe:/app # bind source code
      - frontend_node_modules:/app/node_modules # named volume cho node_modules
    command: ["npm", "run", "dev"]
    networks:
      - appnet

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wellmarket
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

volumes:
  mysql_data:
  frontend_node_modules:
  backend_vendor:

networks:
  appnet:
